# Generated by Django 2.2 on 2023-06-11 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_phone',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('(1[3|4|5|6|7|8|9])\\d{9}', '手机号格式错误')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_index=True, max_length=32, verbose_name='用户名'),
        ),
    ]
